name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y ripgrep libreadline-dev
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: Run tests
        run: nvim -l tests/minit.lua --minitest
